export const IMG_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const RESTAURANTS_API = "https://thingproxy.freeboard.io/fetch/https://www.swiggy.com/dapi/restaurants/list/v5?lat=19.0759837&lng=72.8776559&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
export const MENU_API = "https://thingproxy.freeboard.io/fetch/https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.0759837&lng=72.8776559&restaurantId="
export const MENU_ITEM_IMG = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/"
export const INSTAMART_API = "https://thingproxy.freeboard.io/fetch/https://www.swiggy.com/api/instamart/home?clientId=INSTAMART-APP"
export const INSTAMART_IMG = "https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_200,w_200/"
export const INSTAMART_ITEM_FRONT = "https://www.swiggy.com/api/instamart/category-listing?categoryName="
export const INSTAMART_ITEM_END = "&storeId=1385948&offset=0&filterName=&taxonomyType=All%20Listing"